name: network_video_mock
description: Utility for providing mocked VideoController.network response in Flutter widget tests.
version: 2.0.1
homepage: https://github.com/dkbast/network_video_mock
repository: https://github.com/dkbast/network_video_mock

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
